### ISSUE TITLE
Incompatibility when generating .env based environment project with factory cli

### ISSUE THREAD

**Issue by Croos3r** [DiscordFactory/core#9]
(Am I in the right spot to do this ?)

**How to reproduce:**
- Simply generate a new projet with factory using .env environment when asked.
- Start in dev (in normally after build)

**Problem:**
I think I located the problem: (in Factory.ts)
```ts
const intents: string[] = this.environmentManager.get('INTENTS') // <--
```
Factory is not implemented to get intents as formatted in a .env file and particularly in a factory generated one.

**Solution:**
Simply implement a way to get intents one by one and not as a list. 
(OR make generated .env expose serialized list ?)
I could do this if you allow me to 😉

**Remarks:**

The lib is a great way to create, deploy and maintain, easily and quickly discord bots.
I'm going to use it every time I can and I want to help as good as I can!
Super boulot monsieur Parmantier!

**Comment by LeadcodeDev** [comment]
Thank you Croos3r ! 👋

I have just redeveloped the Core by removing the `.env` environment management.

Indeed, this data format brought too many problems concerning the management of the environment by the core but also much more problematic for the external plugins...

The documentation is not yet up to date but you can try the new version using :
```
npm install @discord-factory/core-next
```

Thank you for your issue !

Have a nice day !
